# Generated by Django 3.0.5 on 2020-04-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_site', models.CharField(max_length=50)),
                ('t_site_url', models.CharField(max_length=100)),
                ('t_site_logo', models.ImageField(upload_to='images/')),
                ('t_blurb', models.TextField(blank=True, default='')),
                ('n_page_order', models.SmallIntegerField()),
            ],
        ),
    ]
