# Generated by Django 3.0.5 on 2020-05-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_received', models.DateTimeField(auto_now_add=True)),
                ('t_name', models.CharField(max_length=60)),
                ('t_message', models.TextField()),
            ],
        ),
    ]
