# Generated by Django 3.0.5 on 2020-05-15 19:50

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_image_path', models.ImageField(upload_to='images/')),
                ('t_details', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrentProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_current_project', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_testimonial', models.CharField(max_length=100)),
                ('t_reviewer', models.CharField(max_length=25)),
                ('a_star_rating', models.SmallIntegerField()),
                ('n_page_order', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
