"""
Django settings for andrewjacobson myprojects.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the myprojects like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('django_andrewjacobson_SECRET_KEY')

# Development settings
DEBUG = True
# ALLOWED_HOSTS = []

# Production settings
# DEBUG = False
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True
# ALLOWED_HOSTS = ['www.andrewjacobson.dev', '3.126.33.137']
# ADMINS = [('Andrew', 'andrew@andrewjacobson.dev')]
# SECURE_HSTS_SECONDS = 3600
# SECURE_SSL_REDIRECT = True


# Application definitions

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myprojects.apps.MyprojectsConfig',
    'myexperience.apps.MyexperienceConfig',
    'contact.apps.ContactConfig',
    'about.apps.AboutConfig',
    'jquery',
    'tinymce',
]

# Middleware definitions

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# Root url configuration

ROOT_URLCONF = 'andrewjacobson.urls'


# Template configurations
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["andrewjacobson/templates/"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'andrewjacobson.wsgi.application'


# Database configurations
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('django_andrewjacobson_DATABASES_ENGINE'),
        'NAME': os.environ.get('django_andrewjacobson_DATABASES_NAME'),
        'USER': os.environ.get('django_andrewjacobson_DATABASES_USER'),
        'PASSWORD': os.environ.get('django_andrewjacobson_DATABASES_PASSWORD'),
        'HOST': os.environ.get('django_andrewjacobson_DATABASES_HOST'),
        'PORT': os.environ.get('django_andrewjacobson_DATABASES_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [
    os.environ.get('django_andrewjacobson_STATICFILES_DIRS')
]


# Media configurations

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# TinyMCE configurations:
# plugins: allow the creation of tables; allow embedded links

TINYMCE_DEFAULT_CONFIG = {
    'plugins': 'table link',
}


# Email configurations

EMAIL_BACKEND = os.environ.get('django_andrewjacobson_EMAIL_BACKEND')
EMAIL_HOST = os.environ.get('django_andrewjacobson_EMAIL_HOST')
EMAIL_USE_TLS = os.environ.get('django_andrewjacobson_EMAIL_USE_TLS')
EMAIL_PORT = os.environ.get('django_andrewjacobson_EMAIL_PORT')
EMAIL_HOST_USER = os.environ.get('django_andrewjacobson_EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('django_andrewjacobson_EMAIL_HOST_PASSWORD')
