# Generated by Django 3.0.5 on 2020-04-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_certification', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_degree', models.CharField(max_length=75)),
                ('t_university', models.CharField(max_length=50)),
                ('t_city', models.CharField(max_length=20)),
                ('c_state', models.CharField(max_length=2)),
                ('t_country', models.CharField(max_length=20)),
                ('d_start', models.DateField()),
                ('d_end', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_position', models.CharField(max_length=50)),
                ('t_company', models.CharField(max_length=50)),
                ('t_city', models.CharField(max_length=20)),
                ('c_state', models.CharField(max_length=2)),
                ('t_country', models.CharField(max_length=20)),
                ('d_start', models.DateField()),
                ('d_end', models.DateField(null=True)),
                ('t_overview', models.TextField()),
                ('t_responsibility_1', models.TextField()),
                ('t_responsibility_2', models.TextField()),
                ('t_responsibility_3', models.TextField()),
                ('t_responsibility_4', models.TextField()),
                ('t_responsibility_5', models.TextField()),
                ('t_responsibility_6', models.TextField()),
                ('t_accomplishment_1', models.TextField()),
                ('t_accomplishment_2', models.TextField()),
                ('t_accomplishment_3', models.TextField()),
                ('t_accomplishment_4', models.TextField()),
                ('t_accomplishment_5', models.TextField()),
                ('t_accomplishment_6', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_type', models.CharField(max_length=1)),
                ('t_skill', models.CharField(max_length=100)),
                ('c_proficiency', models.CharField(max_length=1)),
            ],
        ),
    ]
