# Generated by Django 3.0.5 on 2020-04-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myexperience', '0002_auto_20200413_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='d_end',
            field=models.DateField(default='9999-12-31', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='t_accomplishment_1',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='t_accomplishment_2',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='t_accomplishment_3',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='t_accomplishment_4',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='t_accomplishment_5',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='t_accomplishment_6',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='t_responsibility_1',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='t_responsibility_2',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='t_responsibility_3',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='t_responsibility_4',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='t_responsibility_5',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='t_responsibility_6',
            field=models.TextField(default='', null=True),
        ),
    ]
