# Generated by Django 3.0.5 on 2020-04-13 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myexperience', '0005_auto_20200413_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='t_accomplishment_1',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='t_accomplishment_2',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='t_accomplishment_3',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='t_accomplishment_4',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='t_accomplishment_5',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='t_accomplishment_6',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='t_responsibility_1',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='t_responsibility_2',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='t_responsibility_3',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='t_responsibility_4',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='t_responsibility_5',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='t_responsibility_6',
        ),
        migrations.CreateModel(
            name='ExperienceResponsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_responsibility', models.TextField(blank=True, default='')),
                ('n_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myexperience.Experience')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceAccomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_accomplishment', models.TextField(blank=True, default='')),
                ('n_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myexperience.Experience')),
            ],
        ),
    ]
