# Generated by Django 3.0.5 on 2020-04-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myexperience', '0006_auto_20200413_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceaccomplishment',
            name='n_page_order',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experienceresponsibility',
            name='n_page_order',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
