# Generated by Django 3.0.5 on 2020-04-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myexperience', '0007_auto_20200413_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceresponsibility',
            name='t_title',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
