# Generated by Django 3.0.5 on 2020-04-13 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myexperience', '0008_experienceresponsibility_t_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_experience_type', models.CharField(max_length=1)),
                ('t_title', models.CharField(blank=True, default='', max_length=100)),
                ('t_detail', models.TextField(blank=True, default='')),
                ('n_page_order', models.SmallIntegerField()),
                ('n_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myexperience.Experience')),
            ],
        ),
        migrations.RemoveField(
            model_name='experienceresponsibility',
            name='n_experience',
        ),
        migrations.DeleteModel(
            name='ExperienceAccomplishment',
        ),
        migrations.DeleteModel(
            name='ExperienceResponsibility',
        ),
    ]
