# Generated by Django 3.0.5 on 2020-04-13 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myexperience', '0009_auto_20200413_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencedetail',
            name='n_experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencedetails', to='myexperience.Experience'),
        ),
    ]
