# Generated by Django 3.0.5 on 2020-04-13 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myexperience', '0010_auto_20200413_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceAccomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_accomplishment', models.TextField(blank=True, default='')),
                ('n_page_order', models.SmallIntegerField()),
                ('n_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myexperience.Experience')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceResponsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_title', models.CharField(max_length=100)),
                ('t_responsibility', models.TextField(blank=True, default='')),
                ('n_page_order', models.SmallIntegerField()),
                ('n_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myexperience.Experience')),
            ],
        ),
        migrations.AddField(
            model_name='certification',
            name='n_page_order',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ExperienceDetail',
        ),
    ]
