# Generated by Django 3.0.5 on 2020-04-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myexperience', '0012_experience_t_company_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='t_certification_path',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
