# Generated by Django 3.0.5 on 2020-04-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_played', models.DateTimeField(verbose_name='timestamp of game played')),
                ('i_doubles', models.CharField(max_length=1)),
                ('n_winner_1', models.CharField(max_length=25)),
                ('n_winner_2', models.CharField(max_length=25)),
                ('n_loser_1', models.CharField(max_length=25)),
                ('n_loser_2', models.CharField(max_length=25)),
                ('a_winning_score', models.SmallIntegerField()),
                ('a_losing_score', models.SmallIntegerField()),
            ],
        ),
    ]
