# Generated by Django 3.0.5 on 2020-04-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='i_doubles',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='n_loser_2',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='n_winner_2',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
