# Generated by Django 3.0.5 on 2020-04-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0003_auto_20200411_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Project',
            old_name='t_description',
            new_name='t_details',
        ),
        migrations.AddField(
            model_name='Project',
            name='n_page_order',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='Project',
            name='t_blurb',
            field=models.CharField(default='blurb', max_length=200),
            preserve_default=False,
        ),
    ]
