# Generated by Django 3.0.5 on 2020-04-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0006_auto_20200412_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='t_image_path',
            field=models.ImageField(default='myprojects/static/img/default.png', upload_to='myprojects/static/img/'),
        ),
    ]
