# Generated by Django 3.0.5 on 2020-04-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0015_project_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_Comments',
            new_name='Project_Comment',
        ),
    ]
