# Generated by Django 3.0.5 on 2020-04-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0019_auto_20200413_1134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_Comment',
            new_name='ProjectComment',
        ),
    ]
