# Generated by Django 3.0.5 on 2020-04-17 13:28

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0020_auto_20200413_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='i_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='t_details',
            field=tinymce.models.HTMLField(),
        ),
    ]
