# Generated by Django 3.0.5 on 2020-04-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0021_auto_20200417_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='t_image_path',
            field=models.FilePathField(path='static/img/'),
        ),
    ]
