# Generated by Django 3.0.5 on 2020-04-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0024_auto_20200417_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='t_image_path',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
