# Generated by Django 3.0.5 on 2020-04-20 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0026_auto_20200420_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='t_key_features',
        ),
    ]
