# Generated by Django 3.0.5 on 2020-04-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0028_auto_20200424_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='t_code_url',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
